config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create]

  resources :items, only: [:show, :new]
  resources :ownerships, only: [:create, :destroy]
  
  get 'rankings/want', to: 'rankings#want'
  get 'rankings/have', to: 'rankings#have'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/have.rb
class Have < Ownership
  def self.ranking
    self.group(:item_id).order('count_item_id DESC').limit(10).count(:item_id)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates :code, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :image_url, presence: true, length: { maximum: 255 }
  
  has_many :ownerships
  has_many :users, through: :ownerships
  
  has_many :wants
  has_many :want_users, through: :wants, class_name: 'User', source: :user
  
  has_many :haves, class_name: 'Have'
  has_many :have_users, through: :haves, class_name: 'User', source: :user
end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :ownerships
  has_many :items, through: :ownerships  
  
  has_many :wants
  has_many :want_items, through: :wants, class_name: 'Item', source: :item

  def want(item)
    self.wants.find_or_create_by(item_id: item.id)
  end

  def unwant(item)
    want = self.wants.find_by(item_id: item.id)
    want.destroy if want
  end

  def want?(item)
    self.want_items.include?(item)
  end
  
  has_many :haves, class_name: "Have"
  has_many :have_items, through: :haves, class_name: 'Item', source: :item

  def have(item)
    self.haves.find_or_create_by(item_id: item.id)
  end

  def unhave(item)
    want = self.haves.find_by(item_id: item.id)
    want.destroy if want
  end

  def have?(item)
    self.have_items.include?(item)
  end
end

app/models/want.rb
class Want < Ownership
  def self.ranking
    self.group(:item_id).order('count_item_id DESC').limit(10).count(:item_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

  def read(result)
    code = result['itemCode']
    name = result['itemName']
    url = result['itemUrl']
    image_url = result['mediumImageUrls'].first['imageUrl'].gsub('?_ex=128x128', '')

    return {
      code: code,
      name: name,
      url: url,
      image_url: image_url,
    }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in

  def new
    @items = []

    @keyword = params[:keyword]
    if @keyword
      results = RakutenWebService::Ichiba::Item.search({
        keyword: @keyword,
        imageFlag: 1,
        hits: 20,
      })

      results.each do |result|
        # 扱い易いように Item としてインスタンスを作成する（保存はしない）
        item = Item.find_or_initialize_by(read(result))
        @items << item
      end
    end
  end
  
  def show
    @item = Item.find(params[:id])
    @want_users = @item.want_users
    @have_users = @item.have_users
  end
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  def create
    @item = Item.find_or_initialize_by(code: params[:item_code])

    unless @item.persisted?
      # @item が保存されていない場合、先に @item を保存する
      results = RakutenWebService::Ichiba::Item.search(itemCode: @item.code)

      @item = Item.new(read(results.first))
      @item.save
    end

    # Want 関係として保存
    if params[:type] == 'Want'
      current_user.want(@item)
      flash[:success] = '商品を Want しました。'
    end
    
    # Have 関係として保存
    if params[:type] == 'Have'
      current_user.have(@item)
      flash[:success] = '商品を Have しました。'
    end

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @item = Item.find(params[:item_id])

    if params[:type] == 'Want'
      current_user.unwant(@item) 
      flash[:success] = '商品の Want を解除しました。'
    end
    
    if params[:type] == 'Have'
      current_user.unhave(@item) 
      flash[:success] = '商品の Have を解除しました。'
    end

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def want
    @ranking_counts = Want.ranking
    @items = Item.find(@ranking_counts.keys)
  end
  def have
    @ranking_counts = Have.ranking
    @items = Item.find(@ranking_counts.keys)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @items = Item.order('updated_at DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  def show
    @user = User.find(params[:id])
    @items = @user.items.uniq
    @count_want = @user.want_items.count
    @count_have = @user.have_items.count
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/items/_items.html.erb
<% if items.present? %>
  <div class="row">
    <% items.each do |item| %>
      <div class="item">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= item.image_url %>" alt="" >
            </div>
            <div class="panel-body">
              <% if item.persisted? %>
                <p class="item-title"><%= link_to item.name, item %></p>
              <% else %>
                <p class="item-title"><%= item.name %></p>
              <% end %>
              <div class="buttons text-center">
                <% if logged_in? %>
                  <%= render 'ownerships/want_button', item: item %>
                  <%= render 'ownerships/have_button', item: item %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/items/new.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(new_item_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :keyword, @keyword, class: 'form-control input-lg', placeholder: "キーワードを入力", size: 40 %>
        </div>
        <%= submit_tag '商品を検索', class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'items', items: @items %>

app/views/items/show.html.erb
<div class="row">
  <div class="col-md-3 col-sm-6 col-xs-12 col-md-offset-3">
    <div class="item">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          <img src="<%= @item.image_url %>" alt="">
        </div>
        <div class="panel-body">
          <p class="item-title"><%= @item.name %></p>
          <div class="buttons text-center">
            <% if logged_in? %>
              <%= render 'ownerships/want_button', item: @item %>
              <%= render 'ownerships/have_button', item: @item %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="want-users">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          Wantしたユーザ
        </div>
        <div class="panel-body">
          <% @want_users.each do |user| %>
            <%= link_to user.name, user_path(user) %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="have-users">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          Haveしたユーザ
        </div>
        <div class="panel-body">
          <% @have_users.each do |user| %>
            <%= link_to user.name, user_path(user) %>
          <% end %>
        </div>
      </div>
    </div>
    <p class="text-center"><%= link_to '楽天詳細ページ', @item.url, target: '_blank' %></p>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2016 MONOLIST.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-left" href="/"><img src="/images/logo.png" alt="Monolist"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to new_item_path do %>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                アイテムを追加
              <% end %>
            </li>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
                ランキング
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Wantランキング', rankings_want_path %></li>
                <li><%= link_to 'Haveランキング', rankings_have_path %></li>
              </ul>
            </li>


            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'マイページ', user_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to '新規登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Monolist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/ownerships/_have_button.html.erb
<% if current_user.have?(item) %>
  <%= form_tag(ownership_path(item.id), method: :delete) do %>
    <%= hidden_field_tag :item_id, item.id %>
    <%= hidden_field_tag :type, 'Have' %>
    <%= submit_tag 'Have', class: 'btn btn-success' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :item_code, item.code %>
    <%= hidden_field_tag :type, 'Have' %>
    <%= submit_tag 'Have it', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/ownerships/_want_button.html.erb
<% if current_user.want?(item) %>
  <%= form_tag(ownership_path(item.id), method: :delete) do %>
    <%= hidden_field_tag :item_id, item.id %>
    <%= hidden_field_tag :type, 'Want' %>
    <%= submit_tag 'Want', class: 'btn btn-success' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :item_code, item.code %>
    <%= hidden_field_tag :type, 'Want' %>
    <%= submit_tag 'Want it', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/rankings/have.html.erb
<h1>Haveランキング</h1>
<% if @items.present? %>
  <div class="row">
    <% @items.each_with_index do |item, index| %>
      <div class="item">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= item.image_url %>" alt="" >
            </div>
            <div class="panel-body">
              <p class="item-title"><%= link_to item.name, item %></p>
              <div class="buttons text-center">
                <% if logged_in? %>
                  <%= render 'ownerships/have_button', item: item %>
                <% end %>
              </div>
            </div>
            <div class="panel-footer">
              <p class="text-center"><%= index+1 %>位: <%= @ranking_counts[item.id] %> Haves</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/rankings/want.html.erb
<h1>Wantランキング</h1>
<% if @items.present? %>
  <div class="row">
    <% @items.each_with_index do |item, index| %>
      <div class="item">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= item.image_url %>" alt="" >
            </div>
            <div class="panel-body">
              <p class="item-title"><%= link_to item.name, item %></p>
              <div class="buttons text-center">
                <% if logged_in? %>
                  <%= render 'ownerships/want_button', item: item %>
                <% end %>
              </div>
            </div>
            <div class="panel-footer">
              <p class="text-center"><%= index+1 %>位: <%= @ranking_counts[item.id] %> Wants</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/toppages/index.html.erb
<% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1>素敵なモノと出会う場所</h1>
          <% unless logged_in? %>
            <%= link_to 'モノリストを始める', signup_path, class: 'btn btn-success btn-lg' %>
          <% end %>
      </div>
    </div>
  </div>
<% end %>

<%= render 'items/items', items: @items %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
  <div class="status text-center">
    <ul>
      <li>
        <div class="status-label">WANT</div>
        <div id="want_count" class="status-value">
          <%= @count_want %>
        </div>
      </li>
      <li>
        <div class="status-label">HAVE</div>
        <div id="have_count" class="status-value">
          <%= @count_have %>
        </div>
      </li>
    </ul>
  </div>
</div>
<%= render 'items/items', items: @items %>